const adjectives = [
    { turkish: "Güzel", phonetic: "gü-zèl", translation: "beau, joli", category: "adjectives" },
    { turkish: "Çirkin", phonetic: "tchir-kin", translation: "laid", category: "adjectives" },
    { turkish: "Büyük", phonetic: "bü-yük", translation: "grand", category: "adjectives" },
    { turkish: "Küçük", phonetic: "kü-tchük", translation: "petit", category: "adjectives" },
    { turkish: "İyi", phonetic: "i-yi", translation: "bon, bien", category: "adjectives" },
    { turkish: "Kötü", phonetic: "keû-tü", translation: "mauvais", category: "adjectives" },
    { turkish: "Yeni", phonetic: "yè-ni", translation: "nouveau", category: "adjectives" },
    { turkish: "Eski", phonetic: "ès-ki", translation: "vieux, ancien", category: "adjectives" },
    { turkish: "Uzun", phonetic: "ou-zoun", translation: "long", category: "adjectives" },
    { turkish: "Kısa", phonetic: "k-sa", translation: "court", category: "adjectives" },
    { turkish: "Yüksek", phonetic: "yük-sèk", translation: "haut", category: "adjectives" },
    { turkish: "Alçak", phonetic: "al-tchak", translation: "bas", category: "adjectives" },
    { turkish: "Geniş", phonetic: "ghè-nich", translation: "large", category: "adjectives" },
    { turkish: "Dar", phonetic: "dar", translation: "étroit", category: "adjectives" },
    { turkish: "Kalın", phonetic: "ka-ln", translation: "épais", category: "adjectives" },
    { turkish: "İnce", phonetic: "in-djè", translation: "mince", category: "adjectives" },
    { turkish: "Ağır", phonetic: "a-ır", translation: "lourd", category: "adjectives" },
    { turkish: "Hafif", phonetic: "ha-fif", translation: "léger", category: "adjectives" },
    { turkish: "Sıcak", phonetic: "s-djak", translation: "chaud", category: "adjectives" },
    { turkish: "Soğuk", phonetic: "so-ouk", translation: "froid", category: "adjectives" },
    { turkish: "Ilık", phonetic: "l-k", translation: "tiède", category: "adjectives" },
    { turkish: "Serin", phonetic: "sè-rin", translation: "frais", category: "adjectives" },
    { turkish: "Kuru", phonetic: "kou-rou", translation: "sec", category: "adjectives" },
    { turkish: "Yaş", phonetic: "yach", translation: "humide, mouillé", category: "adjectives" },
    { turkish: "Temiz", phonetic: "tè-miz", translation: "propre", category: "adjectives" },
    { turkish: "Kirli", phonetic: "kir-li", translation: "sale", category: "adjectives" },
    { turkish: "Zengin", phonetic: "zèn-ghin", translation: "riche", category: "adjectives" },
    { turkish: "Fakir", phonetic: "fa-kir", translation: "pauvre", category: "adjectives" },
    { turkish: "Ucuz", phonetic: "ou-djouz", translation: "bon marché", category: "adjectives" },
    { turkish: "Pahalı", phonetic: "pa-ha-l", translation: "cher", category: "adjectives" },
    { turkish: "Kolay", phonetic: "ko-lay", translation: "facile", category: "adjectives" },
    { turkish: "Zor", phonetic: "zor", translation: "difficile", category: "adjectives" },
    { turkish: "Basit", phonetic: "ba-sit", translation: "simple", category: "adjectives" },
    { turkish: "Karmaşık", phonetic: "kar-ma-chk", translation: "compliqué", category: "adjectives" },
    { turkish: "Hızlı", phonetic: "hz-l", translation: "rapide", category: "adjectives" },
    { turkish: "Yavaş", phonetic: "ya-vach", translation: "lent", category: "adjectives" },
    { turkish: "Erken", phonetic: "èr-kèn", translation: "tôt", category: "adjectives" },
    { turkish: "Geç", phonetic: "ghètch", translation: "tard", category: "adjectives" },
    { turkish: "Yakın", phonetic: "ya-kn", translation: "proche", category: "adjectives" },
    { turkish: "Uzak", phonetic: "ou-zak", translation: "loin", category: "adjectives" },
    { turkish: "Aşağı", phonetic: "a-cha-ı", translation: "en bas", category: "adjectives" },
    { turkish: "Yukarı", phonetic: "you-ka-r", translation: "en haut", category: "adjectives" },
    { turkish: "Sağ", phonetic: "sa", translation: "droit (côté)", category: "adjectives" },
    { turkish: "Sol", phonetic: "sol", translation: "gauche", category: "adjectives" },
    { turkish: "İlk", phonetic: "ilk", translation: "premier", category: "adjectives" },
    { turkish: "Son", phonetic: "son", translation: "dernier", category: "adjectives" },
    { turkish: "Dolu", phonetic: "do-lou", translation: "plein", category: "adjectives" },
    { turkish: "Boş", phonetic: "boch", translation: "vide", category: "adjectives" },
    { turkish: "Açık", phonetic: "a-tchk", translation: "ouvert, clair", category: "adjectives" },
    { turkish: "Kapalı", phonetic: "ka-pa-l", translation: "fermé", category: "adjectives" },
    { turkish: "Koyu", phonetic: "ko-you", translation: "foncé", category: "adjectives" },
    { turkish: "Aydınlık", phonetic: "ay-dn-lk", translation: "lumineux", category: "adjectives" },
    { turkish: "Karanlık", phonetic: "ka-ran-lk", translation: "sombre", category: "adjectives" },
    { turkish: "Sessiz", phonetic: "sès-siz", translation: "silencieux", category: "adjectives" },
    { turkish: "Gürültülü", phonetic: "gü-rül-tü-lü", translation: "bruyant", category: "adjectives" },
    { turkish: "Mutlu", phonetic: "mout-lou", translation: "heureux", category: "adjectives" },
    { turkish: "Mutsuz", phonetic: "mout-souz", translation: "malheureux", category: "adjectives" },
    { turkish: "Neşeli", phonetic: "nè-chè-li", translation: "joyeux", category: "adjectives" },
    { turkish: "Üzgün", phonetic: "üz-güün", translation: "triste", category: "adjectives" },
    { turkish: "Kızgın", phonetic: "kz-gn", translation: "en colère", category: "adjectives" },
    { turkish: "Sakin", phonetic: "sa-kin", translation: "calme", category: "adjectives" },
    { turkish: "Sinirli", phonetic: "si-nir-li", translation: "nerveux", category: "adjectives" },
    { turkish: "Yorgun", phonetic: "yor-ghoun", translation: "fatigué", category: "adjectives" },
    { turkish: "Dinç", phonetic: "dintch", translation: "en forme", category: "adjectives" },
    { turkish: "Hasta", phonetic: "has-ta", translation: "malade", category: "adjectives" },
    { turkish: "Sağlıklı", phonetic: "sa-lk-l", translation: "en bonne santé", category: "adjectives" },
    { turkish: "Güçlü", phonetic: "güütch-lü", translation: "fort", category: "adjectives" },
    { turkish: "Zayıf", phonetic: "za-yf", translation: "faible", category: "adjectives" },
    { turkish: "Cesur", phonetic: "djè-sour", translation: "courageux", category: "adjectives" },
    { turkish: "Korkak", phonetic: "kor-kak", translation: "lâche", category: "adjectives" },
    { turkish: "Akıllı", phonetic: "a-kl-l", translation: "intelligent", category: "adjectives" },
    { turkish: "Aptal", phonetic: "ap-tal", translation: "stupide", category: "adjectives" },
    { turkish: "Zeki", phonetic: "zè-ki", translation: "intelligent", category: "adjectives" },
    { turkish: "Ahmak", phonetic: "ah-mak", translation: "idiot", category: "adjectives" },
    { turkish: "Nazik", phonetic: "na-zik", translation: "poli, gentil", category: "adjectives" },
    { turkish: "Kaba", phonetic: "ka-ba", translation: "grossier", category: "adjectives" },
    { turkish: "Kibar", phonetic: "ki-bar", translation: "courtois", category: "adjectives" },
    { turkish: "Dürüst", phonetic: "dü-rüst", translation: "honnête", category: "adjectives" },
    { turkish: "Yalancı", phonetic: "ya-lan-dj", translation: "menteur", category: "adjectives" },
    { turkish: "Cömert", phonetic: "djeû-mèrt", translation: "généreux", category: "adjectives" },
    { turkish: "Cimri", phonetic: "djim-ri", translation: "avare", category: "adjectives" },
    { turkish: "Çalışkan", phonetic: "tcha-lch-kan", translation: "travailleur", category: "adjectives" },
    { turkish: "Tembel", phonetic: "tèm-bèl", translation: "paresseux", category: "adjectives" },
    { turkish: "Dikkatli", phonetic: "dik-kat-li", translation: "attentif", category: "adjectives" },
    { turkish: "Dikkatsiz", phonetic: "dik-kat-siz", translation: "inattentif", category: "adjectives" },
    { turkish: "Sabırlı", phonetic: "sa-br-l", translation: "patient", category: "adjectives" },
    { turkish: "Sabırsız", phonetic: "sa-br-sz", translation: "impatient", category: "adjectives" },
    { turkish: "Ünlü", phonetic: "ün-lü", translation: "célèbre", category: "adjectives" },
    { turkish: "Meşhur", phonetic: "mèch-hour", translation: "connu", category: "adjectives" },
    { turkish: "Önemli", phonetic: "eû-nèm-li", translation: "important", category: "adjectives" },
    { turkish: "Önemsiz", phonetic: "eû-nèm-siz", translation: "sans importance", category: "adjectives" },
    { turkish: "Tehlikeli", phonetic: "tèh-li-kè-li", translation: "dangereux", category: "adjectives" },
    { turkish: "Güvenli", phonetic: "gü-vèn-li", translation: "sûr", category: "adjectives" },
    { turkish: "Doğru", phonetic: "do-rou", translation: "correct, vrai", category: "adjectives" },
    { turkish: "Yanlış", phonetic: "yan-lch", translation: "faux", category: "adjectives" },
    { turkish: "Gerçek", phonetic: "ghèr-tchèk", translation: "vrai, réel", category: "adjectives" },
    { turkish: "Sahte", phonetic: "sah-tè", translation: "faux", category: "adjectives" },
    { turkish: "Taze", phonetic: "ta-zè", translation: "frais", category: "adjectives" },
    { turkish: "Bayat", phonetic: "ba-yat", translation: "rassis", category: "adjectives" },
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = adjectives;
}
