(function() {
    if (window.expressions) return; // Already loaded

    window.expressions = [
    { turkish: "Merhaba", phonetic: "mèr-ha-ba", translation: "bonjour", category: "expressions" },
    { turkish: "Selam", phonetic: "sè-lam", translation: "salut", category: "expressions" },
    { turkish: "Günaydın", phonetic: "güün-ay-dn", translation: "bonjour (matin)", category: "expressions" },
    { turkish: "İyi günler", phonetic: "i-yi güün-lèr", translation: "bonne journée", category: "expressions" },
    { turkish: "İyi akşamlar", phonetic: "i-yi ak-cham-lar", translation: "bonsoir", category: "expressions" },
    { turkish: "İyi geceler", phonetic: "i-yi ghè-djè-lèr", translation: "bonne nuit", category: "expressions" },
    { turkish: "Hoşça kal", phonetic: "hoch-tcha kal", translation: "au revoir (celui qui part)", category: "expressions" },
    { turkish: "Güle güle", phonetic: "gü-lè gü-lè", translation: "au revoir (celui qui reste)", category: "expressions" },
    { turkish: "Görüşürüz", phonetic: "gueû-rü-chü-rüz", translation: "à bientôt", category: "expressions" },
    { turkish: "Teşekkürler", phonetic: "tè-chèk-kür-lèr", translation: "merci", category: "expressions" },
    { turkish: "Teşekkür ederim", phonetic: "tè-chèk-kür è-dè-rim", translation: "merci (formel)", category: "expressions" },
    { turkish: "Çok teşekkürler", phonetic: "tchok tè-chèk-kür-lèr", translation: "merci beaucoup", category: "expressions" },
    { turkish: "Rica ederim", phonetic: "ri-dja è-dè-rim", translation: "de rien, je vous en prie", category: "expressions" },
    { turkish: "Bir şey değil", phonetic: "bir chèy dè-il", translation: "ce n'est rien", category: "expressions" },
    { turkish: "Lütfen", phonetic: "lüt-fèn", translation: "s'il vous plaît", category: "expressions" },
    { turkish: "Afedersiniz", phonetic: "a-fè-dèr-si-niz", translation: "excusez-moi, pardon", category: "expressions" },
    { turkish: "Özür dilerim", phonetic: "eû-zür di-lè-rim", translation: "je m'excuse", category: "expressions" },
    { turkish: "Pardon", phonetic: "par-don", translation: "pardon", category: "expressions" },
    { turkish: "Evet", phonetic: "è-vèt", translation: "oui", category: "expressions" },
    { turkish: "Hayır", phonetic: "ha-yr", translation: "non", category: "expressions" },
    { turkish: "Tamam", phonetic: "ta-mam", translation: "d'accord, OK", category: "expressions" },
    { turkish: "Peki", phonetic: "pè-ki", translation: "d'accord", category: "expressions" },
    { turkish: "Olur", phonetic: "o-lour", translation: "ça va, d'accord", category: "expressions" },
    { turkish: "Olmaz", phonetic: "ol-maz", translation: "ce n'est pas possible", category: "expressions" },
    { turkish: "Nasılsınız?", phonetic: "na-sl-s-nz", translation: "comment allez-vous?", category: "expressions" },
    { turkish: "Nasılsın?", phonetic: "na-sl-sn", translation: "comment vas-tu?", category: "expressions" },
    { turkish: "İyiyim", phonetic: "i-yi-yim", translation: "je vais bien", category: "expressions" },
    { turkish: "İyiyim, teşekkürler", phonetic: "i-yi-yim, tè-chèk-kür-lèr", translation: "je vais bien, merci", category: "expressions" },
    { turkish: "Sen nasılsın?", phonetic: "sèn na-sl-sn", translation: "et toi?", category: "expressions" },
    { turkish: "Ne var ne yok?", phonetic: "nè var nè yok", translation: "quoi de neuf?", category: "expressions" },
    { turkish: "İyi, sağ ol", phonetic: "i-yi, sa ol", translation: "bien, merci", category: "expressions" },
    { turkish: "Adın ne?", phonetic: "a-dn nè", translation: "quel est ton nom?", category: "expressions" },
    { turkish: "Adınız ne?", phonetic: "a-d-nz nè", translation: "quel est votre nom?", category: "expressions" },
    { turkish: "Benim adım...", phonetic: "bè-nim a-dm...", translation: "mon nom est...", category: "expressions" },
    { turkish: "Memnun oldum", phonetic: "mèm-noun ol-doum", translation: "enchanté", category: "expressions" },
    { turkish: "Tanıştığımıza memnun oldum", phonetic: "ta-nch-t-ı-m-za mèm-noun ol-doum", translation: "ravi de vous rencontrer", category: "expressions" },
    { turkish: "Hoş bulduk", phonetic: "hoch boul-douk", translation: "bienvenue (réponse)", category: "expressions" },
    { turkish: "Hoş geldiniz", phonetic: "hoch ghèl-di-niz", translation: "bienvenue", category: "expressions" },
    { turkish: "Afiyet olsun", phonetic: "a-fi-yèt ol-soun", translation: "bon appétit", category: "expressions" },
    { turkish: "Şerefe", phonetic: "chè-rè-fè", translation: "santé! (toast)", category: "expressions" },
    { turkish: "Geçmiş olsun", phonetic: "ghètch-mich ol-soun", translation: "prompt rétablissement", category: "expressions" },
    { turkish: "İyi yolculuklar", phonetic: "i-yi yol-djou-louk-lar", translation: "bon voyage", category: "expressions" },
    { turkish: "İyi şanslar", phonetic: "i-yi chans-lar", translation: "bonne chance", category: "expressions" },
    { turkish: "Kolay gelsin", phonetic: "ko-lay ghèl-sin", translation: "bon courage (au travail)", category: "expressions" },
    { turkish: "Hayırlı işler", phonetic: "ha-yr-l ich-lèr", translation: "bon travail", category: "expressions" },
    { turkish: "Tebrikler", phonetic: "tèb-rik-lèr", translation: "félicitations", category: "expressions" },
    { turkish: "Doğum günün kutlu olsun", phonetic: "do-oum gü-nün kout-lou ol-soun", translation: "joyeux anniversaire", category: "expressions" },
    { turkish: "Mutlu yıllar", phonetic: "mout-lou yl-lar", translation: "bonne année", category: "expressions" },
    { turkish: "İyi bayramlar", phonetic: "i-yi bay-ram-lar", translation: "bonne fête", category: "expressions" },
    { turkish: "Sağlıcakla kal", phonetic: "sa-l-djak-la kal", translation: "reste en bonne santé", category: "expressions" },
    { turkish: "Allah'a ısmarladık", phonetic: "al-la-ha s-mar-la-dk", translation: "au revoir (religieux)", category: "expressions" },
    { turkish: "Ne demek istiyorsun?", phonetic: "nè dè-mèk is-ti-yor-soun", translation: "que veux-tu dire?", category: "expressions" },
    { turkish: "Anlamadım", phonetic: "an-la-ma-dm", translation: "je n'ai pas compris", category: "expressions" },
    { turkish: "Tekrar söyler misiniz?", phonetic: "tèk-rar seû-lèr mi-si-niz", translation: "pouvez-vous répéter?", category: "expressions" },
    { turkish: "Yavaş konuşur musunuz?", phonetic: "ya-vach ko-nou-chour mou-sou-nouz", translation: "pouvez-vous parler lentement?", category: "expressions" },
    { turkish: "Türkçe bilmiyorum", phonetic: "türk-tchè bil-mi-yo-roum", translation: "je ne parle pas turc", category: "expressions" },
    { turkish: "İngilizce biliyor musunuz?", phonetic: "in-ghi-liz-djè bi-li-yor mou-sou-nouz", translation: "parlez-vous anglais?", category: "expressions" },
    { turkish: "Fransızca biliyor musunuz?", phonetic: "fran-sz-dja bi-li-yor mou-sou-nouz", translation: "parlez-vous français?", category: "expressions" },
    { turkish: "Yardım eder misiniz?", phonetic: "yar-dm è-dèr mi-si-niz", translation: "pouvez-vous m'aider?", category: "expressions" },
    { turkish: "Elbette", phonetic: "èl-bèt-tè", translation: "bien sûr", category: "expressions" },
    { turkish: "Tabii", phonetic: "ta-bi", translation: "bien sûr", category: "expressions" },
    { turkish: "Maalesef", phonetic: "ma-a-lè-sèf", translation: "malheureusement", category: "expressions" },
    { turkish: "Belki", phonetic: "bèl-ki", translation: "peut-être", category: "expressions" },
    { turkish: "Muhtemelen", phonetic: "mouh-tè-mè-lèn", translation: "probablement", category: "expressions" },
    { turkish: "Kesinlikle", phonetic: "kè-sin-lik-lè", translation: "certainement", category: "expressions" },
    { turkish: "Asla", phonetic: "as-la", translation: "jamais", category: "expressions" },
    { turkish: "Her zaman", phonetic: "hèr za-man", translation: "toujours", category: "expressions" },
    { turkish: "Bazen", phonetic: "ba-zèn", translation: "parfois", category: "expressions" },
    { turkish: "Sık sık", phonetic: "sk sk", translation: "souvent", category: "expressions" },
    { turkish: "Nadiren", phonetic: "na-di-rèn", translation: "rarement", category: "expressions" },
    { turkish: "Şimdi", phonetic: "chim-di", translation: "maintenant", category: "expressions" },
    { turkish: "Sonra", phonetic: "son-ra", translation: "après", category: "expressions" },
    { turkish: "Önce", phonetic: "eûn-djè", translation: "avant", category: "expressions" },
    { turkish: "Daha sonra", phonetic: "da-ha son-ra", translation: "plus tard", category: "expressions" },
    { turkish: "Hemen", phonetic: "hè-mèn", translation: "tout de suite", category: "expressions" },
    { turkish: "Birazdan", phonetic: "bi-raz-dan", translation: "dans un moment", category: "expressions" },
    { turkish: "Bugün", phonetic: "bou-güün", translation: "aujourd'hui", category: "expressions" },
    { turkish: "Dün", phonetic: "düün", translation: "hier", category: "expressions" },
    { turkish: "Yarın", phonetic: "ya-rn", translation: "demain", category: "expressions" },
    { turkish: "Geçen hafta", phonetic: "ghè-tchèn haf-ta", translation: "la semaine dernière", category: "expressions" },
    { turkish: "Gelecek hafta", phonetic: "ghè-lè-djèk haf-ta", translation: "la semaine prochaine", category: "expressions" },
    { turkish: "Ne kadar?", phonetic: "nè ka-dar", translation: "combien?", category: "expressions" },
    { turkish: "Kaç para?", phonetic: "katch pa-ra", translation: "combien ça coûte?", category: "expressions" },
    { turkish: "Çok pahalı", phonetic: "tchok pa-ha-l", translation: "trop cher", category: "expressions" },
    { turkish: "Nerede?", phonetic: "nè-rè-dè", translation: "où?", category: "expressions" },
    { turkish: "Ne zaman?", phonetic: "nè za-man", translation: "quand?", category: "expressions" },
    { turkish: "Nasıl?", phonetic: "na-sl", translation: "comment?", category: "expressions" },
    { turkish: "Neden?", phonetic: "nè-dèn", translation: "pourquoi?", category: "expressions" },
    { turkish: "Kim?", phonetic: "kim", translation: "qui?", category: "expressions" },
    { turkish: "Ne?", phonetic: "nè", translation: "quoi?", category: "expressions" },
    { turkish: "Hangi?", phonetic: "han-ghi", translation: "lequel?", category: "expressions" },
    { turkish: "Acelem var", phonetic: "a-djè-lèm var", translation: "je suis pressé", category: "expressions" },
    { turkish: "Acele etme", phonetic: "a-djè-lè èt-mè", translation: "ne te presse pas", category: "expressions" },
    { turkish: "Bekle", phonetic: "bèk-lè", translation: "attends", category: "expressions" },
    { turkish: "Bir dakika", phonetic: "bir da-ki-ka", translation: "une minute", category: "expressions" },
    { turkish: "Çok güzel", phonetic: "tchok gü-zèl", translation: "très beau", category: "expressions" },
    { turkish: "Harika", phonetic: "ha-ri-ka", translation: "génial", category: "expressions" },
    { turkish: "Mükemmel", phonetic: "mü-kèm-mèl", translation: "parfait", category: "expressions" },
    { turkish: "Berbat", phonetic: "bèr-bat", translation: "horrible", category: "expressions" },
    { turkish: "Korkunç", phonetic: "kor-kountch", translation: "affreux", category: "expressions" },
];

// Export to window for browser use
window.expressions = expressions;

    // Export for Node.js if needed
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = window.expressions;
    }
})();
