const familyPeople = [
    { turkish: "anne", phonetic: "an-ne", translation: "mère", category: "nouns" },
    { turkish: "baba", phonetic: "ba-ba", translation: "père", category: "nouns" },
    { turkish: "çocuk", phonetic: "tcho-djuk", translation: "enfant", category: "nouns" },
    { turkish: "oğul", phonetic: "o-oul", translation: "fils", category: "nouns" },
    { turkish: "kız", phonetic: "keuz", translation: "fille", category: "nouns" },
    { turkish: "kardeş", phonetic: "kar-dech", translation: "frère/sœur", category: "nouns" },
    { turkish: "ağabey", phonetic: "a-a-bey", translation: "grand frère", category: "nouns" },
    { turkish: "abla", phonetic: "ab-la", translation: "grande sœur", category: "nouns" },
    { turkish: "erkek kardeş", phonetic: "er-kek kar-dech", translation: "frère", category: "nouns" },
    { turkish: "kız kardeş", phonetic: "keuz kar-dech", translation: "sœur", category: "nouns" },
    { turkish: "dede", phonetic: "de-de", translation: "grand-père", category: "nouns" },
    { turkish: "büyükanne", phonetic: "bu-yuk-an-ne", translation: "grand-mère", category: "nouns" },
    { turkish: "büyükbaba", phonetic: "bu-yuk-ba-ba", translation: "grand-père", category: "nouns" },
    { turkish: "nine", phonetic: "ni-ne", translation: "grand-mère", category: "nouns" },
    { turkish: "torun", phonetic: "to-run", translation: "petit-enfant", category: "nouns" },
    { turkish: "amca", phonetic: "am-dja", translation: "oncle paternel", category: "nouns" },
    { turkish: "dayı", phonetic: "da-yeu", translation: "oncle maternel", category: "nouns" },
    { turkish: "teyze", phonetic: "tey-ze", translation: "tante maternelle", category: "nouns" },
    { turkish: "hala", phonetic: "ha-la", translation: "tante paternelle", category: "nouns" },
    { turkish: "yeğen", phonetic: "ye-en", translation: "neveu/nièce", category: "nouns" },
    { turkish: "kuzen", phonetic: "ku-zen", translation: "cousin/cousine", category: "nouns" },
    { turkish: "eş", phonetic: "ech", translation: "conjoint/e", category: "nouns" },
    { turkish: "koca", phonetic: "ko-dja", translation: "mari", category: "nouns" },
    { turkish: "karı", phonetic: "ka-reu", translation: "femme/épouse", category: "nouns" },
    { turkish: "aile", phonetic: "a-i-le", translation: "famille", category: "nouns" },
    { turkish: "bebek", phonetic: "be-bek", translation: "bébé", category: "nouns" },
    { turkish: "genç", phonetic: "guendj", translation: "jeune", category: "nouns" },
    { turkish: "yaşlı", phonetic: "yach-leu", translation: "âgé/e", category: "nouns" },
    { turkish: "adam", phonetic: "a-dam", translation: "homme", category: "nouns" },
    { turkish: "kadın", phonetic: "ka-deun", translation: "femme", category: "nouns" },
    { turkish: "erkek", phonetic: "er-kek", translation: "homme/mâle", category: "nouns" },
    { turkish: "kişi", phonetic: "ki-chi", translation: "personne", category: "nouns" },
    { turkish: "insan", phonetic: "in-san", translation: "être humain", category: "nouns" },
    { turkish: "doktor", phonetic: "dok-tor", translation: "médecin", category: "nouns" },
    { turkish: "hemşire", phonetic: "hem-chi-re", translation: "infirmier/ère", category: "nouns" },
    { turkish: "öğretmen", phonetic: "eu-ret-men", translation: "enseignant/e", category: "nouns" },
    { turkish: "öğrenci", phonetic: "eu-ren-dji", translation: "étudiant/e", category: "nouns" },
    { turkish: "avukat", phonetic: "a-vu-kat", translation: "avocat/e", category: "nouns" },
    { turkish: "mühendis", phonetic: "mu-hen-dis", translation: "ingénieur", category: "nouns" },
    { turkish: "polis", phonetic: "po-lis", translation: "policier", category: "nouns" },
    { turkish: "asker", phonetic: "as-ker", translation: "soldat", category: "nouns" },
    { turkish: "işçi", phonetic: "ich-tchi", translation: "ouvrier/ère", category: "nouns" },
    { turkish: "memur", phonetic: "me-mur", translation: "fonctionnaire", category: "nouns" },
    { turkish: "patron", phonetic: "pat-ron", translation: "patron", category: "nouns" },
    { turkish: "müdür", phonetic: "mu-dur", translation: "directeur", category: "nouns" },
    { turkish: "sekreter", phonetic: "sek-re-ter", translation: "secrétaire", category: "nouns" },
    { turkish: "garson", phonetic: "gar-son", translation: "serveur", category: "nouns" },
    { turkish: "aşçı", phonetic: "ach-tcheu", translation: "cuisinier", category: "nouns" },
    { turkish: "berber", phonetic: "ber-ber", translation: "coiffeur", category: "nouns" },
    { turkish: "kuaför", phonetic: "ku-a-feur", translation: "coiffeur/euse", category: "nouns" },
    { turkish: "şoför", phonetic: "cho-feur", translation: "chauffeur", category: "nouns" },
    { turkish: "pilot", phonetic: "pi-lot", translation: "pilote", category: "nouns" },
    { turkish: "hostes", phonetic: "hos-tes", translation: "hôtesse de l'air", category: "nouns" },
    { turkish: "kaptan", phonetic: "kap-tan", translation: "capitaine", category: "nouns" },
    { turkish: "ressam", phonetic: "res-sam", translation: "peintre", category: "nouns" },
    { turkish: "sanatçı", phonetic: "sa-nat-tcheu", translation: "artiste", category: "nouns" },
    { turkish: "müzisyen", phonetic: "mu-zis-yen", translation: "musicien", category: "nouns" },
    { turkish: "şarkıcı", phonetic: "char-keu-djeu", translation: "chanteur/euse", category: "nouns" },
    { turkish: "oyuncu", phonetic: "o-yun-dju", translation: "acteur/actrice", category: "nouns" },
    { turkish: "yazar", phonetic: "ya-zar", translation: "écrivain", category: "nouns" },
    { turkish: "gazeteci", phonetic: "ga-ze-te-dji", translation: "journaliste", category: "nouns" },
    { turkish: "fotoğrafçı", phonetic: "fo-to-raf-tcheu", translation: "photographe", category: "nouns" },
    { turkish: "satıcı", phonetic: "sa-teu-djeu", translation: "vendeur/euse", category: "nouns" },
    { turkish: "müşteri", phonetic: "much-te-ri", translation: "client/e", category: "nouns" },
    { turkish: "banker", phonetic: "ban-ker", translation: "banquier", category: "nouns" },
    { turkish: "muhasebeci", phonetic: "mu-ha-se-be-dji", translation: "comptable", category: "nouns" },
    { turkish: "eczacı", phonetic: "ed-za-djeu", translation: "pharmacien/ne", category: "nouns" },
    { turkish: "dişçi", phonetic: "dich-tchi", translation: "dentiste", category: "nouns" },
    { turkish: "veteriner", phonetic: "ve-te-ri-ner", translation: "vétérinaire", category: "nouns" },
    { turkish: "çiftçi", phonetic: "tchift-tchi", translation: "agriculteur", category: "nouns" },
    { turkish: "bahçıvan", phonetic: "bah-tcheu-van", translation: "jardinier", category: "nouns" },
    { turkish: "terzi", phonetic: "ter-zi", translation: "tailleur/couturier", category: "nouns" },
    { turkish: "elektrikçi", phonetic: "e-lek-trik-tchi", translation: "électricien", category: "nouns" },
    { turkish: "tesisatçı", phonetic: "te-si-sat-tcheu", translation: "plombier", category: "nouns" },
    { turkish: "marangoz", phonetic: "ma-ran-goz", translation: "menuisier", category: "nouns" },
    { turkish: "boyacı", phonetic: "bo-ya-djeu", translation: "peintre en bâtiment", category: "nouns" },
    { turkish: "tamirci", phonetic: "ta-mir-dji", translation: "réparateur", category: "nouns" },
    { turkish: "postacı", phonetic: "pos-ta-djeu", translation: "facteur", category: "nouns" },
    { turkish: "temizlikçi", phonetic: "te-miz-lik-tchi", translation: "agent de nettoyage", category: "nouns" },
    { turkish: "güvenlik görevlisi", phonetic: "gu-ven-lik geu-rev-li-si", translation: "agent de sécurité", category: "nouns" },
    { turkish: "itfaiyeci", phonetic: "it-fa-i-ye-dji", translation: "pompier", category: "nouns" },
    { turkish: "paramedik", phonetic: "pa-ra-me-dik", translation: "ambulancier", category: "nouns" },
    { turkish: "hâkim", phonetic: "ha-kim", translation: "juge", category: "nouns" },
    { turkish: "savcı", phonetic: "sav-djeu", translation: "procureur", category: "nouns" },
    { turkish: "asistan", phonetic: "a-sis-tan", translation: "assistant/e", category: "nouns" },
    { turkish: "danışman", phonetic: "da-neuch-man", translation: "conseiller", category: "nouns" },
    { turkish: "rehber", phonetic: "reh-ber", translation: "guide", category: "nouns" },
    { turkish: "tercüman", phonetic: "ter-dju-man", translation: "interprète", category: "nouns" },
    { turkish: "sporcu", phonetic: "spor-dju", translation: "sportif/ve", category: "nouns" },
    { turkish: "antrenör", phonetic: "ant-re-neur", translation: "entraîneur", category: "nouns" },
    { turkish: "hakem", phonetic: "ha-kem", translation: "arbitre", category: "nouns" },
    { turkish: "arkadaş", phonetic: "ar-ka-dach", translation: "ami/e", category: "nouns" },
    { turkish: "komşu", phonetic: "kom-chu", translation: "voisin/e", category: "nouns" },
    { turkish: "misafir", phonetic: "mi-sa-fir", translation: "invité/e", category: "nouns" },
    { turkish: "yabancı", phonetic: "ya-ban-djeu", translation: "étranger", category: "nouns" },
    { turkish: "tanıdık", phonetic: "ta-neu-deuk", translation: "connaissance", category: "nouns" },
    { turkish: "sevgili", phonetic: "sev-gi-li", translation: "amoureux/euse", category: "nouns" },
    { turkish: "nişanlı", phonetic: "ni-chan-leu", translation: "fiancé/e", category: "nouns" },
    { turkish: "damat", phonetic: "da-mat", translation: "marié/gendre", category: "nouns" },
    { turkish: "gelin", phonetic: "ge-lin", translation: "mariée/belle-fille", category: "nouns" }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = familyPeople;
}
