const nounsFood = [
    { turkish: "Ekmek", phonetic: "èk-mèk", translation: "pain", category: "nouns" },
    { turkish: "Et", phonetic: "èt", translation: "viande", category: "nouns" },
    { turkish: "Peynir", phonetic: "pèy-nir", translation: "fromage", category: "nouns" },
    { turkish: "Meyve", phonetic: "mèy-vè", translation: "fruit", category: "nouns" },
    { turkish: "Sebze", phonetic: "sèb-zè", translation: "légume", category: "nouns" },
    { turkish: "Elma", phonetic: "èl-ma", translation: "pomme", category: "nouns" },
    { turkish: "Armut", phonetic: "ar-mout", translation: "poire", category: "nouns" },
    { turkish: "Portakal", phonetic: "por-ta-kal", translation: "orange", category: "nouns" },
    { turkish: "Muz", phonetic: "mouz", translation: "banane", category: "nouns" },
    { turkish: "Üzüm", phonetic: "ü-züm", translation: "raisin", category: "nouns" },
    { turkish: "Kiraz", phonetic: "ki-raz", translation: "cerise", category: "nouns" },
    { turkish: "Çilek", phonetic: "tchi-lèk", translation: "fraise", category: "nouns" },
    { turkish: "Kavun", phonetic: "ka-voun", translation: "melon", category: "nouns" },
    { turkish: "Karpuz", phonetic: "kar-pouz", translation: "pastèque", category: "nouns" },
    { turkish: "Şeftali", phonetic: "chèf-ta-li", translation: "pêche", category: "nouns" },
    { turkish: "Kayısı", phonetic: "ka-y-s", translation: "abricot", category: "nouns" },
    { turkish: "Erik", phonetic: "è-rik", translation: "prune", category: "nouns" },
    { turkish: "İncir", phonetic: "in-djir", translation: "figue", category: "nouns" },
    { turkish: "Nar", phonetic: "nar", translation: "grenade", category: "nouns" },
    { turkish: "Ayva", phonetic: "ay-va", translation: "coing", category: "nouns" },
    { turkish: "Limon", phonetic: "li-mon", translation: "citron", category: "nouns" },
    { turkish: "Mandalina", phonetic: "man-da-li-na", translation: "mandarine", category: "nouns" },
    { turkish: "Ananas", phonetic: "a-na-nas", translation: "ananas", category: "nouns" },
    { turkish: "Domates", phonetic: "do-ma-tès", translation: "tomate", category: "nouns" },
    { turkish: "Salatalık", phonetic: "sa-la-ta-lk", translation: "concombre", category: "nouns" },
    { turkish: "Biber", phonetic: "bi-bèr", translation: "poivron", category: "nouns" },
    { turkish: "Patlıcan", phonetic: "pat-l-djan", translation: "aubergine", category: "nouns" },
    { turkish: "Kabak", phonetic: "ka-bak", translation: "courgette, courge", category: "nouns" },
    { turkish: "Havuç", phonetic: "ha-voutch", translation: "carotte", category: "nouns" },
    { turkish: "Patates", phonetic: "pa-ta-tès", translation: "pomme de terre", category: "nouns" },
    { turkish: "Soğan", phonetic: "so-an", translation: "oignon", category: "nouns" },
    { turkish: "Sarımsak", phonetic: "sa-rms-ak", translation: "ail", category: "nouns" },
    { turkish: "Marul", phonetic: "ma-roul", translation: "laitue", category: "nouns" },
    { turkish: "Ispanak", phonetic: "s-pa-nak", translation: "épinards", category: "nouns" },
    { turkish: "Maydanoz", phonetic: "may-da-noz", translation: "persil", category: "nouns" },
    { turkish: "Nane", phonetic: "na-nè", translation: "menthe", category: "nouns" },
    { turkish: "Kekik", phonetic: "kè-kik", translation: "thym", category: "nouns" },
    { turkish: "Fasulye", phonetic: "fa-soul-yè", translation: "haricot", category: "nouns" },
    { turkish: "Nohut", phonetic: "no-hout", translation: "pois chiche", category: "nouns" },
    { turkish: "Mercimek", phonetic: "mèr-dji-mèk", translation: "lentille", category: "nouns" },
    { turkish: "Pirinç", phonetic: "pi-rintch", translation: "riz", category: "nouns" },
    { turkish: "Bulgur", phonetic: "boul-ghour", translation: "boulgour", category: "nouns" },
    { turkish: "Makarna", phonetic: "ma-kar-na", translation: "pâtes", category: "nouns" },
    { turkish: "Un", phonetic: "oun", translation: "farine", category: "nouns" },
    { turkish: "Şeker", phonetic: "chè-kèr", translation: "sucre", category: "nouns" },
    { turkish: "Tuz", phonetic: "touz", translation: "sel", category: "nouns" },
    { turkish: "Karabiber", phonetic: "ka-ra-bi-bèr", translation: "poivre noir", category: "nouns" },
    { turkish: "Yağ", phonetic: "ya", translation: "huile, graisse", category: "nouns" },
    { turkish: "Zeytinyağı", phonetic: "zèy-tin-ya-ı", translation: "huile d'olive", category: "nouns" },
    { turkish: "Tereyağı", phonetic: "tè-rè-ya-ı", translation: "beurre", category: "nouns" },
    { turkish: "Süt", phonetic: "süt", translation: "lait", category: "nouns" },
    { turkish: "Yoğurt", phonetic: "yo-ourt", translation: "yaourt", category: "nouns" },
    { turkish: "Yumurta", phonetic: "you-mour-ta", translation: "œuf", category: "nouns" },
    { turkish: "Bal", phonetic: "bal", translation: "miel", category: "nouns" },
    { turkish: "Reçel", phonetic: "rè-tchèl", translation: "confiture", category: "nouns" },
    { turkish: "Zeytin", phonetic: "zèy-tin", translation: "olive", category: "nouns" },
    { turkish: "Sığır eti", phonetic: "s-ır è-ti", translation: "bœuf", category: "nouns" },
    { turkish: "Kuzu eti", phonetic: "kou-zou è-ti", translation: "agneau", category: "nouns" },
    { turkish: "Tavuk eti", phonetic: "ta-vouk è-ti", translation: "poulet", category: "nouns" },
    { turkish: "Balık", phonetic: "ba-lk", translation: "poisson", category: "nouns" },
    { turkish: "Levrek", phonetic: "lèv-rèk", translation: "bar (poisson)", category: "nouns" },
    { turkish: "Çipura", phonetic: "tchi-pou-ra", translation: "daurade", category: "nouns" },
    { turkish: "Hamsi", phonetic: "ham-si", translation: "anchois", category: "nouns" },
    { turkish: "Karides", phonetic: "ka-ri-dès", translation: "crevette", category: "nouns" },
    { turkish: "Midye", phonetic: "mid-yè", translation: "moule", category: "nouns" },
    { turkish: "Ahtapot", phonetic: "ah-ta-pot", translation: "poulpe", category: "nouns" },
    { turkish: "Kalamar", phonetic: "ka-la-mar", translation: "calmar", category: "nouns" },
    { turkish: "Çay", phonetic: "tchay", translation: "thé", category: "nouns" },
    { turkish: "Kahve", phonetic: "kah-vè", translation: "café", category: "nouns" },
    { turkish: "Şarap", phonetic: "cha-rap", translation: "vin", category: "nouns" },
    { turkish: "Bira", phonetic: "bi-ra", translation: "bière", category: "nouns" },
    { turkish: "Rakı", phonetic: "ra-k", translation: "raki (alcool turc)", category: "nouns" },
    { turkish: "Meyve suyu", phonetic: "mèy-vè sou-you", translation: "jus de fruit", category: "nouns" },
    { turkish: "Ayran", phonetic: "ay-ran", translation: "ayran (boisson au yaourt)", category: "nouns" },
    { turkish: "Çorba", phonetic: "tchor-ba", translation: "soupe", category: "nouns" },
    { turkish: "Salata", phonetic: "sa-la-ta", translation: "salade", category: "nouns" },
    { turkish: "Pilav", phonetic: "pi-lav", translation: "riz pilaf", category: "nouns" },
    { turkish: "Köfte", phonetic: "keûf-tè", translation: "boulette de viande", category: "nouns" },
    { turkish: "Kebap", phonetic: "kè-bap", translation: "kebab", category: "nouns" },
    { turkish: "Döner", phonetic: "deû-nèr", translation: "döner kebab", category: "nouns" },
    { turkish: "Lahmacun", phonetic: "lah-ma-djoun", translation: "lahmacun (pizza turque)", category: "nouns" },
    { turkish: "Pide", phonetic: "pi-dè", translation: "pide (pain turc)", category: "nouns" },
    { turkish: "Börek", phonetic: "beû-rèk", translation: "börek (feuilleté)", category: "nouns" },
    { turkish: "Dolma", phonetic: "dol-ma", translation: "dolma (feuille farcie)", category: "nouns" },
    { turkish: "Sarma", phonetic: "sar-ma", translation: "sarma (rouleau farci)", category: "nouns" },
    { turkish: "Meze", phonetic: "mè-zè", translation: "meze (apéritif)", category: "nouns" },
    { turkish: "İmam bayıldı", phonetic: "i-mam ba-yl-d", translation: "imam bayildi (aubergine farcie)", category: "nouns" },
    { turkish: "Mantı", phonetic: "man-t", translation: "manti (ravioli turc)", category: "nouns" },
    { turkish: "Gözleme", phonetic: "gueûz-lè-mè", translation: "gözleme (crêpe turque)", category: "nouns" },
    { turkish: "Tatlı", phonetic: "tat-l", translation: "dessert", category: "nouns" },
    { turkish: "Baklava", phonetic: "bak-la-va", translation: "baklava", category: "nouns" },
    { turkish: "Kadayıf", phonetic: "ka-da-yf", translation: "kadayif (dessert)", category: "nouns" },
    { turkish: "Sütlaç", phonetic: "süt-latch", translation: "riz au lait", category: "nouns" },
    { turkish: "Lokum", phonetic: "lo-koum", translation: "loukoum", category: "nouns" },
    { turkish: "Dondurma", phonetic: "don-dour-ma", translation: "glace", category: "nouns" },
    { turkish: "Pasta", phonetic: "pas-ta", translation: "gâteau", category: "nouns" },
    { turkish: "Kurabiye", phonetic: "kou-ra-bi-yè", translation: "biscuit", category: "nouns" },
    { turkish: "Çikolata", phonetic: "tchi-ko-la-ta", translation: "chocolat", category: "nouns" },
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = nounsFood;
}
