(function() {
    if (window.nounsCommon) return; // Already loaded

    window.nounsCommon = [
    { turkish: "Ev", phonetic: "èv", translation: "maison", category: "nouns" },
    { turkish: "Araba", phonetic: "a-ra-ba", translation: "voiture", category: "nouns" },
    { turkish: "Kitap", phonetic: "ki-tap", translation: "livre", category: "nouns" },
    { turkish: "Su", phonetic: "sou", translation: "eau", category: "nouns" },
    { turkish: "Yemek", phonetic: "yè-mèk", translation: "nourriture, repas", category: "nouns" },
    { turkish: "İnsan", phonetic: "in-san", translation: "être humain, personne", category: "nouns" },
    { turkish: "Adam", phonetic: "a-dam", translation: "homme", category: "nouns" },
    { turkish: "Kadın", phonetic: "ka-dn", translation: "femme", category: "nouns" },
    { turkish: "Çocuk", phonetic: "tcho-djouk", translation: "enfant", category: "nouns" },
    { turkish: "Bebek", phonetic: "bè-bèk", translation: "bébé", category: "nouns" },
    { turkish: "Anne", phonetic: "an-nè", translation: "mère", category: "nouns" },
    { turkish: "Baba", phonetic: "ba-ba", translation: "père", category: "nouns" },
    { turkish: "Kardeş", phonetic: "kar-dèch", translation: "frère/sœur", category: "nouns" },
    { turkish: "Aile", phonetic: "a-i-lè", translation: "famille", category: "nouns" },
    { turkish: "Arkadaş", phonetic: "ar-ka-dach", translation: "ami", category: "nouns" },
    { turkish: "Şehir", phonetic: "chè-hir", translation: "ville", category: "nouns" },
    { turkish: "Ülke", phonetic: "ül-kè", translation: "pays", category: "nouns" },
    { turkish: "Dünya", phonetic: "dün-ya", translation: "monde", category: "nouns" },
    { turkish: "Gökyüzü", phonetic: "gueûk-yü-zü", translation: "ciel", category: "nouns" },
    { turkish: "Güneş", phonetic: "gü-nèch", translation: "soleil", category: "nouns" },
    { turkish: "Ay", phonetic: "ay", translation: "lune", category: "nouns" },
    { turkish: "Yıldız", phonetic: "yl-dz", translation: "étoile", category: "nouns" },
    { turkish: "Gün", phonetic: "güün", translation: "jour", category: "nouns" },
    { turkish: "Gece", phonetic: "ghè-djè", translation: "nuit", category: "nouns" },
    { turkish: "Sabah", phonetic: "sa-bah", translation: "matin", category: "nouns" },
    { turkish: "Öğle", phonetic: "eu-lè", translation: "midi", category: "nouns" },
    { turkish: "Akşam", phonetic: "ak-cham", translation: "soir", category: "nouns" },
    { turkish: "Hafta", phonetic: "haf-ta", translation: "semaine", category: "nouns" },
    { turkish: "Ay", phonetic: "ay", translation: "mois", category: "nouns" },
    { turkish: "Yıl", phonetic: "yl", translation: "année", category: "nouns" },
    { turkish: "Saat", phonetic: "sa-at", translation: "heure, montre", category: "nouns" },
    { turkish: "Dakika", phonetic: "da-ki-ka", translation: "minute", category: "nouns" },
    { turkish: "Saniye", phonetic: "sa-ni-yè", translation: "seconde", category: "nouns" },
    { turkish: "Zaman", phonetic: "za-man", translation: "temps", category: "nouns" },
    { turkish: "Yer", phonetic: "yèr", translation: "lieu, place, sol", category: "nouns" },
    { turkish: "Oda", phonetic: "o-da", translation: "chambre", category: "nouns" },
    { turkish: "Kapı", phonetic: "ka-p", translation: "porte", category: "nouns" },
    { turkish: "Pencere", phonetic: "pèn-djè-rè", translation: "fenêtre", category: "nouns" },
    { turkish: "Masa", phonetic: "ma-sa", translation: "table", category: "nouns" },
    { turkish: "Sandalye", phonetic: "san-dal-yè", translation: "chaise", category: "nouns" },
    { turkish: "Yatak", phonetic: "ya-tak", translation: "lit", category: "nouns" },
    { turkish: "Dolap", phonetic: "do-lap", translation: "armoire", category: "nouns" },
    { turkish: "Duvar", phonetic: "dou-var", translation: "mur", category: "nouns" },
    { turkish: "Tavan", phonetic: "ta-van", translation: "plafond", category: "nouns" },
    { turkish: "Zemin", phonetic: "zè-min", translation: "sol, plancher", category: "nouns" },
    { turkish: "Yol", phonetic: "yol", translation: "chemin, route", category: "nouns" },
    { turkish: "Sokak", phonetic: "so-kak", translation: "rue", category: "nouns" },
    { turkish: "Cadde", phonetic: "djad-dè", translation: "avenue", category: "nouns" },
    { turkish: "Köprü", phonetic: "keûp-rü", translation: "pont", category: "nouns" },
    { turkish: "Bina", phonetic: "bi-na", translation: "bâtiment", category: "nouns" },
    { turkish: "Okul", phonetic: "o-koul", translation: "école", category: "nouns" },
    { turkish: "Üniversite", phonetic: "ü-ni-vèr-si-tè", translation: "université", category: "nouns" },
    { turkish: "Hastane", phonetic: "has-ta-nè", translation: "hôpital", category: "nouns" },
    { turkish: "Market", phonetic: "mar-kèt", translation: "supermarché", category: "nouns" },
    { turkish: "Dükkan", phonetic: "dük-kan", translation: "magasin", category: "nouns" },
    { turkish: "Restoran", phonetic: "rès-to-ran", translation: "restaurant", category: "nouns" },
    { turkish: "Kafe", phonetic: "ka-fè", translation: "café", category: "nouns" },
    { turkish: "Otel", phonetic: "o-tèl", translation: "hôtel", category: "nouns" },
    { turkish: "Park", phonetic: "park", translation: "parc", category: "nouns" },
    { turkish: "Bahçe", phonetic: "bah-tchè", translation: "jardin", category: "nouns" },
    { turkish: "Ağaç", phonetic: "a-atch", translation: "arbre", category: "nouns" },
    { turkish: "Çiçek", phonetic: "tchi-tchèk", translation: "fleur", category: "nouns" },
    { turkish: "Yaprak", phonetic: "yap-rak", translation: "feuille", category: "nouns" },
    { turkish: "Hayvan", phonetic: "hay-van", translation: "animal", category: "nouns" },
    { turkish: "Köpek", phonetic: "keû-pèk", translation: "chien", category: "nouns" },
    { turkish: "Kedi", phonetic: "kè-di", translation: "chat", category: "nouns" },
    { turkish: "Kuş", phonetic: "kouch", translation: "oiseau", category: "nouns" },
    { turkish: "Balık", phonetic: "ba-lk", translation: "poisson", category: "nouns" },
    { turkish: "At", phonetic: "at", translation: "cheval", category: "nouns" },
    { turkish: "İnek", phonetic: "i-nèk", translation: "vache", category: "nouns" },
    { turkish: "Koyun", phonetic: "ko-youn", translation: "mouton", category: "nouns" },
    { turkish: "Tavuk", phonetic: "ta-vouk", translation: "poulet, poule", category: "nouns" },
    { turkish: "Para", phonetic: "pa-ra", translation: "argent", category: "nouns" },
    { turkish: "Lira", phonetic: "li-ra", translation: "livre (monnaie)", category: "nouns" },
    { turkish: "İş", phonetic: "ich", translation: "travail, affaire", category: "nouns" },
    { turkish: "Görev", phonetic: "gueû-rèv", translation: "tâche, mission", category: "nouns" },
    { turkish: "Meslek", phonetic: "mès-lèk", translation: "métier, profession", category: "nouns" },
    { turkish: "Doktor", phonetic: "dok-tor", translation: "docteur", category: "nouns" },
    { turkish: "Öğretmen", phonetic: "eu-rèt-mèn", translation: "professeur", category: "nouns" },
    { turkish: "Öğrenci", phonetic: "eu-rèn-dji", translation: "étudiant", category: "nouns" },
    { turkish: "Müdür", phonetic: "mü-dür", translation: "directeur", category: "nouns" },
    { turkish: "İşçi", phonetic: "ich-tchi", translation: "ouvrier", category: "nouns" },
    { turkish: "Memur", phonetic: "mè-mour", translation: "fonctionnaire", category: "nouns" },
    { turkish: "Telefon", phonetic: "tè-lè-fon", translation: "téléphone", category: "nouns" },
    { turkish: "Bilgisayar", phonetic: "bil-ghi-sa-yar", translation: "ordinateur", category: "nouns" },
    { turkish: "Televizyon", phonetic: "tè-lè-viz-yon", translation: "télévision", category: "nouns" },
    { turkish: "Radyo", phonetic: "rad-yo", translation: "radio", category: "nouns" },
    { turkish: "Müzik", phonetic: "mü-zik", translation: "musique", category: "nouns" },
    { turkish: "Film", phonetic: "film", translation: "film", category: "nouns" },
    { turkish: "Gazete", phonetic: "gha-zè-tè", translation: "journal", category: "nouns" },
    { turkish: "Dergi", phonetic: "dèr-ghi", translation: "magazine", category: "nouns" },
    { turkish: "Kalem", phonetic: "ka-lèm", translation: "stylo, crayon", category: "nouns" },
    { turkish: "Kağıt", phonetic: "ka-ıt", translation: "papier", category: "nouns" },
    { turkish: "Defter", phonetic: "dèf-tèr", translation: "cahier", category: "nouns" },
    { turkish: "Çanta", phonetic: "tchan-ta", translation: "sac", category: "nouns" },
    { turkish: "Elbise", phonetic: "èl-bi-sè", translation: "robe, vêtement", category: "nouns" },
    { turkish: "Pantolon", phonetic: "pan-to-lon", translation: "pantalon", category: "nouns" },
    { turkish: "Gömlek", phonetic: "gueûm-lèk", translation: "chemise", category: "nouns" },
];

// Export to window for browser use
window.nounsCommon = nounsCommon;

    // Export for Node.js if needed
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = window.nounsCommon;
    }
})();
