const places = [
    { turkish: "ev", phonetic: "ev", translation: "maison", category: "nouns" },
    { turkish: "okul", phonetic: "o-kul", translation: "école", category: "nouns" },
    { turkish: "hastane", phonetic: "has-ta-ne", translation: "hôpital", category: "nouns" },
    { turkish: "market", phonetic: "mar-ket", translation: "supermarché", category: "nouns" },
    { turkish: "restoran", phonetic: "res-to-ran", translation: "restaurant", category: "nouns" },
    { turkish: "kafe", phonetic: "ka-fe", translation: "café", category: "nouns" },
    { turkish: "park", phonetic: "park", translation: "parc", category: "nouns" },
    { turkish: "bahçe", phonetic: "bah-tche", translation: "jardin", category: "nouns" },
    { turkish: "şehir", phonetic: "che-hir", translation: "ville", category: "nouns" },
    { turkish: "köy", phonetic: "keuy", translation: "village", category: "nouns" },
    { turkish: "ülke", phonetic: "ul-ke", translation: "pays", category: "nouns" },
    { turkish: "dünya", phonetic: "dun-ya", translation: "monde", category: "nouns" },
    { turkish: "cadde", phonetic: "djad-de", translation: "avenue", category: "nouns" },
    { turkish: "sokak", phonetic: "so-kak", translation: "rue", category: "nouns" },
    { turkish: "meydan", phonetic: "mey-dan", translation: "place", category: "nouns" },
    { turkish: "köprü", phonetic: "keu-pru", translation: "pont", category: "nouns" },
    { turkish: "bina", phonetic: "bi-na", translation: "bâtiment", category: "nouns" },
    { turkish: "daire", phonetic: "da-i-re", translation: "appartement", category: "nouns" },
    { turkish: "oda", phonetic: "o-da", translation: "chambre", category: "nouns" },
    { turkish: "mutfak", phonetic: "mut-fak", translation: "cuisine", category: "nouns" },
    { turkish: "banyo", phonetic: "ban-yo", translation: "salle de bain", category: "nouns" },
    { turkish: "salon", phonetic: "sa-lon", translation: "salon", category: "nouns" },
    { turkish: "yatak odası", phonetic: "ya-tak o-da-seu", translation: "chambre à coucher", category: "nouns" },
    { turkish: "tuvalet", phonetic: "tu-va-let", translation: "toilettes", category: "nouns" },
    { turkish: "balkon", phonetic: "bal-kon", translation: "balcon", category: "nouns" },
    { turkish: "çatı", phonetic: "tcha-teu", translation: "toit", category: "nouns" },
    { turkish: "bodrum", phonetic: "bod-rum", translation: "cave/sous-sol", category: "nouns" },
    { turkish: "kapı", phonetic: "ka-peu", translation: "porte", category: "nouns" },
    { turkish: "pencere", phonetic: "pen-dje-re", translation: "fenêtre", category: "nouns" },
    { turkish: "duvar", phonetic: "du-var", translation: "mur", category: "nouns" },
    { turkish: "zemin", phonetic: "ze-min", translation: "sol", category: "nouns" },
    { turkish: "merdiven", phonetic: "mer-di-ven", translation: "escalier", category: "nouns" },
    { turkish: "asansör", phonetic: "a-san-seur", translation: "ascenseur", category: "nouns" },
    { turkish: "ofis", phonetic: "o-fis", translation: "bureau", category: "nouns" },
    { turkish: "fabrika", phonetic: "fab-ri-ka", translation: "usine", category: "nouns" },
    { turkish: "dükkân", phonetic: "duk-kian", translation: "boutique", category: "nouns" },
    { turkish: "mağaza", phonetic: "ma-a-za", translation: "magasin", category: "nouns" },
    { turkish: "çarşı", phonetic: "tchar-cheu", translation: "marché/bazar", category: "nouns" },
    { turkish: "alışveriş merkezi", phonetic: "a-leuch-ve-rich mer-ke-zi", translation: "centre commercial", category: "nouns" },
    { turkish: "banka", phonetic: "ban-ka", translation: "banque", category: "nouns" },
    { turkish: "postane", phonetic: "pos-ta-ne", translation: "bureau de poste", category: "nouns" },
    { turkish: "eczane", phonetic: "ed-za-ne", translation: "pharmacie", category: "nouns" },
    { turkish: "kütüphane", phonetic: "ku-tup-ha-ne", translation: "bibliothèque", category: "nouns" },
    { turkish: "müze", phonetic: "mu-ze", translation: "musée", category: "nouns" },
    { turkish: "sinema", phonetic: "si-ne-ma", translation: "cinéma", category: "nouns" },
    { turkish: "tiyatro", phonetic: "ti-yat-ro", translation: "théâtre", category: "nouns" },
    { turkish: "opera", phonetic: "o-pe-ra", translation: "opéra", category: "nouns" },
    { turkish: "konser salonu", phonetic: "kon-ser sa-lo-nu", translation: "salle de concert", category: "nouns" },
    { turkish: "stadyum", phonetic: "stad-yum", translation: "stade", category: "nouns" },
    { turkish: "spor salonu", phonetic: "spor sa-lo-nu", translation: "salle de sport", category: "nouns" },
    { turkish: "havuz", phonetic: "ha-vuz", translation: "piscine", category: "nouns" },
    { turkish: "plaj", phonetic: "plaj", translation: "plage", category: "nouns" },
    { turkish: "otel", phonetic: "o-tel", translation: "hôtel", category: "nouns" },
    { turkish: "motel", phonetic: "mo-tel", translation: "motel", category: "nouns" },
    { turkish: "pansiyon", phonetic: "pan-si-yon", translation: "pension", category: "nouns" },
    { turkish: "lokanta", phonetic: "lo-kan-ta", translation: "restaurant", category: "nouns" },
    { turkish: "bar", phonetic: "bar", translation: "bar", category: "nouns" },
    { turkish: "pub", phonetic: "pab", translation: "pub", category: "nouns" },
    { turkish: "pastane", phonetic: "pas-ta-ne", translation: "pâtisserie", category: "nouns" },
    { turkish: "fırın", phonetic: "feu-reun", translation: "boulangerie", category: "nouns" },
    { turkish: "kasap", phonetic: "ka-sap", translation: "boucherie", category: "nouns" },
    { turkish: "manav", phonetic: "ma-nav", translation: "primeur", category: "nouns" },
    { turkish: "berber", phonetic: "ber-ber", translation: "coiffeur", category: "nouns" },
    { turkish: "kuaför", phonetic: "ku-a-feur", translation: "salon de coiffure", category: "nouns" },
    { turkish: "güzellik salonu", phonetic: "gu-zel-lik sa-lo-nu", translation: "salon de beauté", category: "nouns" },
    { turkish: "cami", phonetic: "dja-mi", translation: "mosquée", category: "nouns" },
    { turkish: "kilise", phonetic: "ki-li-se", translation: "église", category: "nouns" },
    { turkish: "sinagog", phonetic: "si-na-gog", translation: "synagogue", category: "nouns" },
    { turkish: "tapınak", phonetic: "ta-peu-nak", translation: "temple", category: "nouns" },
    { turkish: "mezarlık", phonetic: "me-zar-leuk", translation: "cimetière", category: "nouns" },
    { turkish: "havalimanı", phonetic: "ha-va-li-ma-neu", translation: "aéroport", category: "nouns" },
    { turkish: "istasyon", phonetic: "is-tas-yon", translation: "gare", category: "nouns" },
    { turkish: "tren istasyonu", phonetic: "tren is-tas-yo-nu", translation: "gare ferroviaire", category: "nouns" },
    { turkish: "otobüs durağı", phonetic: "o-to-bus du-ra-eu", translation: "arrêt de bus", category: "nouns" },
    { turkish: "metro", phonetic: "met-ro", translation: "métro", category: "nouns" },
    { turkish: "liman", phonetic: "li-man", translation: "port", category: "nouns" },
    { turkish: "iskele", phonetic: "is-ke-le", translation: "quai/embarcadère", category: "nouns" },
    { turkish: "otopark", phonetic: "o-to-park", translation: "parking", category: "nouns" },
    { turkish: "garaj", phonetic: "ga-raj", translation: "garage", category: "nouns" },
    { turkish: "benzin istasyonu", phonetic: "ben-zin is-tas-yo-nu", translation: "station-service", category: "nouns" },
    { turkish: "üniversite", phonetic: "u-ni-ver-si-te", translation: "université", category: "nouns" },
    { turkish: "kolej", phonetic: "ko-lej", translation: "collège", category: "nouns" },
    { turkish: "lise", phonetic: "li-se", translation: "lycée", category: "nouns" },
    { turkish: "ilkokul", phonetic: "il-ko-kul", translation: "école primaire", category: "nouns" },
    { turkish: "anaokulu", phonetic: "a-na-o-ku-lu", translation: "école maternelle", category: "nouns" },
    { turkish: "kreş", phonetic: "krech", translation: "crèche", category: "nouns" },
    { turkish: "laboratuvar", phonetic: "la-bo-ra-tu-var", translation: "laboratoire", category: "nouns" },
    { turkish: "klinik", phonetic: "kli-nik", translation: "clinique", category: "nouns" },
    { turkish: "acil servis", phonetic: "a-djil ser-vis", translation: "urgences", category: "nouns" },
    { turkish: "polis karakolu", phonetic: "po-lis ka-ra-ko-lu", translation: "commissariat", category: "nouns" },
    { turkish: "itfaiye", phonetic: "it-fa-i-ye", translation: "caserne de pompiers", category: "nouns" },
    { turkish: "mahkeme", phonetic: "mah-ke-me", translation: "tribunal", category: "nouns" },
    { turkish: "hapishane", phonetic: "ha-pis-ha-ne", translation: "prison", category: "nouns" },
    { turkish: "elçilik", phonetic: "el-tchi-lik", translation: "ambassade", category: "nouns" },
    { turkish: "konsolosluk", phonetic: "kon-so-los-luk", translation: "consulat", category: "nouns" },
    { turkish: "belediye", phonetic: "be-le-di-ye", translation: "mairie", category: "nouns" },
    { turkish: "köşk", phonetic: "keuchk", translation: "kiosque/pavillon", category: "nouns" },
    { turkish: "saray", phonetic: "sa-ray", translation: "palais", category: "nouns" },
    { turkish: "kale", phonetic: "ka-le", translation: "château fort", category: "nouns" },
    { turkish: "kule", phonetic: "ku-le", translation: "tour", category: "nouns" }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = places;
}
