const technologyMisc = [
    { turkish: "bilgisayar", phonetic: "bil-gi-sa-yar", translation: "ordinateur", category: "nouns" },
    { turkish: "telefon", phonetic: "te-le-fon", translation: "téléphone", category: "nouns" },
    { turkish: "cep telefonu", phonetic: "djep te-le-fo-nu", translation: "téléphone portable", category: "nouns" },
    { turkish: "tablet", phonetic: "tab-let", translation: "tablette", category: "nouns" },
    { turkish: "internet", phonetic: "in-ter-net", translation: "internet", category: "nouns" },
    { turkish: "web sitesi", phonetic: "web si-te-si", translation: "site web", category: "nouns" },
    { turkish: "e-posta", phonetic: "e-pos-ta", translation: "courriel", category: "nouns" },
    { turkish: "mesaj", phonetic: "me-saj", translation: "message", category: "nouns" },
    { turkish: "uygulama", phonetic: "uy-gu-la-ma", translation: "application", category: "nouns" },
    { turkish: "program", phonetic: "prog-ram", translation: "programme", category: "nouns" },
    { turkish: "yazılım", phonetic: "ya-zeu-leum", translation: "logiciel", category: "nouns" },
    { turkish: "donanım", phonetic: "do-na-neum", translation: "matériel", category: "nouns" },
    { turkish: "ekran", phonetic: "ek-ran", translation: "écran", category: "nouns" },
    { turkish: "klavye", phonetic: "klav-ye", translation: "clavier", category: "nouns" },
    { turkish: "fare", phonetic: "fa-re", translation: "souris", category: "nouns" },
    { turkish: "hoparlör", phonetic: "ho-par-leur", translation: "haut-parleur", category: "nouns" },
    { turkish: "kulaklık", phonetic: "ku-lak-leuk", translation: "casque/écouteurs", category: "nouns" },
    { turkish: "mikrofon", phonetic: "mik-ro-fon", translation: "microphone", category: "nouns" },
    { turkish: "kamera", phonetic: "ka-me-ra", translation: "caméra", category: "nouns" },
    { turkish: "fotoğraf makinesi", phonetic: "fo-to-raf ma-ki-ne-si", translation: "appareil photo", category: "nouns" },
    { turkish: "video", phonetic: "vi-de-o", translation: "vidéo", category: "nouns" },
    { turkish: "ses", phonetic: "ses", translation: "son", category: "nouns" },
    { turkish: "görüntü", phonetic: "geu-run-tu", translation: "image", category: "nouns" },
    { turkish: "dosya", phonetic: "dos-ya", translation: "fichier", category: "nouns" },
    { turkish: "klasör", phonetic: "kla-seur", translation: "dossier", category: "nouns" },
    { turkish: "veri", phonetic: "ve-ri", translation: "données", category: "nouns" },
    { turkish: "bilgi", phonetic: "bil-gi", translation: "information", category: "nouns" },
    { turkish: "şifre", phonetic: "chif-re", translation: "mot de passe", category: "nouns" },
    { turkish: "kullanıcı adı", phonetic: "kul-la-neu-djeu a-deu", translation: "nom d'utilisateur", category: "nouns" },
    { turkish: "hesap", phonetic: "he-sap", translation: "compte", category: "nouns" },
    { turkish: "ağ", phonetic: "a", translation: "réseau", category: "nouns" },
    { turkish: "bağlantı", phonetic: "ba-lan-teu", translation: "connexion", category: "nouns" },
    { turkish: "indirme", phonetic: "in-dir-me", translation: "téléchargement", category: "nouns" },
    { turkish: "yükleme", phonetic: "yuk-le-me", translation: "chargement/envoi", category: "nouns" },
    { turkish: "arama", phonetic: "a-ra-ma", translation: "recherche", category: "nouns" },
    { turkish: "tarayıcı", phonetic: "ta-ra-yeu-djeu", translation: "navigateur", category: "nouns" },
    { turkish: "sosyal medya", phonetic: "sos-yal med-ya", translation: "médias sociaux", category: "nouns" },
    { turkish: "televizyon", phonetic: "te-le-viz-yon", translation: "télévision", category: "nouns" },
    { turkish: "radyo", phonetic: "rad-yo", translation: "radio", category: "nouns" },
    { turkish: "müzik çalar", phonetic: "mu-zik tcha-lar", translation: "lecteur de musique", category: "nouns" },
    { turkish: "şarj aleti", phonetic: "charj a-le-ti", translation: "chargeur", category: "nouns" },
    { turkish: "pil", phonetic: "pil", translation: "pile/batterie", category: "nouns" },
    { turkish: "elektrik", phonetic: "e-lek-trik", translation: "électricité", category: "nouns" },
    { turkish: "fiş", phonetic: "fich", translation: "prise/fiche", category: "nouns" },
    { turkish: "kablo", phonetic: "kab-lo", translation: "câble", category: "nouns" },
    { turkish: "uzaktan kumanda", phonetic: "u-zak-tan ku-man-da", translation: "télécommande", category: "nouns" },
    { turkish: "düğme", phonetic: "du-me", translation: "bouton", category: "nouns" },
    { turkish: "anahtar", phonetic: "a-nah-tar", translation: "clé/interrupteur", category: "nouns" },
    { turkish: "lamba", phonetic: "lam-ba", translation: "lampe", category: "nouns" },
    { turkish: "ışık", phonetic: "eu-cheuk", translation: "lumière", category: "nouns" },
    { turkish: "kalem", phonetic: "ka-lem", translation: "stylo", category: "nouns" },
    { turkish: "kitap", phonetic: "ki-tap", translation: "livre", category: "nouns" },
    { turkish: "defter", phonetic: "def-ter", translation: "cahier", category: "nouns" },
    { turkish: "kâğıt", phonetic: "kia-eut", translation: "papier", category: "nouns" },
    { turkish: "gazete", phonetic: "ga-ze-te", translation: "journal", category: "nouns" },
    { turkish: "dergi", phonetic: "der-gi", translation: "magazine", category: "nouns" },
    { turkish: "çanta", phonetic: "tchan-ta", translation: "sac", category: "nouns" },
    { turkish: "cüzdan", phonetic: "djuz-dan", translation: "portefeuille", category: "nouns" },
    { turkish: "para", phonetic: "pa-ra", translation: "argent", category: "nouns" },
    { turkish: "kredi kartı", phonetic: "kre-di kar-teu", translation: "carte de crédit", category: "nouns" },
    { turkish: "saat", phonetic: "sa-at", translation: "montre", category: "nouns" },
    { turkish: "gözlük", phonetic: "geuz-luk", translation: "lunettes", category: "nouns" },
    { turkish: "şemsiye", phonetic: "chem-si-ye", translation: "parapluie", category: "nouns" },
    { turkish: "anahtar", phonetic: "a-nah-tar", translation: "clé", category: "nouns" },
    { turkish: "kilit", phonetic: "ki-lit", translation: "serrure", category: "nouns" },
    { turkish: "araba", phonetic: "a-ra-ba", translation: "voiture", category: "nouns" },
    { turkish: "otobüs", phonetic: "o-to-bus", translation: "bus", category: "nouns" },
    { turkish: "tren", phonetic: "tren", translation: "train", category: "nouns" },
    { turkish: "uçak", phonetic: "u-tchak", translation: "avion", category: "nouns" },
    { turkish: "gemi", phonetic: "ge-mi", translation: "bateau/navire", category: "nouns" },
    { turkish: "bisiklet", phonetic: "bi-sik-let", translation: "vélo", category: "nouns" },
    { turkish: "motosiklet", phonetic: "mo-to-sik-let", translation: "moto", category: "nouns" },
    { turkish: "taksi", phonetic: "tak-si", translation: "taxi", category: "nouns" },
    { turkish: "ambulans", phonetic: "am-bu-lans", translation: "ambulance", category: "nouns" },
    { turkish: "itfaiye arabası", phonetic: "it-fa-i-ye a-ra-ba-seu", translation: "camion de pompiers", category: "nouns" },
    { turkish: "polis arabası", phonetic: "po-lis a-ra-ba-seu", translation: "voiture de police", category: "nouns" },
    { turkish: "trafik", phonetic: "tra-fik", translation: "trafic", category: "nouns" },
    { turkish: "yol", phonetic: "yol", translation: "route/chemin", category: "nouns" },
    { turkish: "köşe", phonetic: "keu-che", translation: "coin", category: "nouns" },
    { turkish: "sınır", phonetic: "seu-neur", translation: "frontière/limite", category: "nouns" },
    { turkish: "harita", phonetic: "ha-ri-ta", translation: "carte", category: "nouns" },
    { turkish: "plan", phonetic: "plan", translation: "plan", category: "nouns" },
    { turkish: "bilet", phonetic: "bi-let", translation: "billet", category: "nouns" },
    { turkish: "pasaport", phonetic: "pa-sa-port", translation: "passeport", category: "nouns" },
    { turkish: "vize", phonetic: "vi-ze", translation: "visa", category: "nouns" },
    { turkish: "kimlik", phonetic: "kim-lik", translation: "carte d'identité", category: "nouns" },
    { turkish: "fiyat", phonetic: "fi-yat", translation: "prix", category: "nouns" },
    { turkish: "ücret", phonetic: "uj-ret", translation: "tarif/frais", category: "nouns" },
    { turkish: "indirim", phonetic: "in-di-rim", translation: "réduction", category: "nouns" },
    { turkish: "vergi", phonetic: "ver-gi", translation: "taxe/impôt", category: "nouns" },
    { turkish: "banka", phonetic: "ban-ka", translation: "banque", category: "nouns" },
    { turkish: "ATM", phonetic: "a-te-em", translation: "distributeur automatique", category: "nouns" },
    { turkish: "makbuz", phonetic: "mak-buz", translation: "reçu", category: "nouns" },
    { turkish: "fatura", phonetic: "fa-tu-ra", translation: "facture", category: "nouns" },
    { turkish: "sözleşme", phonetic: "seuz-lech-me", translation: "contrat", category: "nouns" },
    { turkish: "belge", phonetic: "bel-gue", translation: "document", category: "nouns" },
    { turkish: "form", phonetic: "form", translation: "formulaire", category: "nouns" },
    { turkish: "imza", phonetic: "im-za", translation: "signature", category: "nouns" }
];

// Export to window for browser use
window.technologyMisc = technologyMisc;

if (typeof module !== 'undefined' && module.exports) {
    module.exports = technologyMisc;
}
