const timeNumbers = [
    { turkish: "zaman", phonetic: "za-man", translation: "temps", category: "nouns" },
    { turkish: "saat", phonetic: "sa-at", translation: "heure", category: "nouns" },
    { turkish: "dakika", phonetic: "da-ki-ka", translation: "minute", category: "nouns" },
    { turkish: "saniye", phonetic: "sa-ni-ye", translation: "seconde", category: "nouns" },
    { turkish: "gün", phonetic: "gun", translation: "jour", category: "nouns" },
    { turkish: "hafta", phonetic: "haf-ta", translation: "semaine", category: "nouns" },
    { turkish: "ay", phonetic: "ay", translation: "mois", category: "nouns" },
    { turkish: "yıl", phonetic: "yeul", translation: "an/année", category: "nouns" },
    { turkish: "asır", phonetic: "a-seur", translation: "siècle", category: "nouns" },
    { turkish: "bugün", phonetic: "bu-gun", translation: "aujourd'hui", category: "nouns" },
    { turkish: "dün", phonetic: "dun", translation: "hier", category: "nouns" },
    { turkish: "yarın", phonetic: "ya-reun", translation: "demain", category: "nouns" },
    { turkish: "evvelki gün", phonetic: "ev-vel-ki gun", translation: "avant-hier", category: "nouns" },
    { turkish: "öbür gün", phonetic: "eu-bur gun", translation: "après-demain", category: "nouns" },
    { turkish: "şimdi", phonetic: "chim-di", translation: "maintenant", category: "nouns" },
    { turkish: "şu an", phonetic: "chu an", translation: "en ce moment", category: "nouns" },
    { turkish: "sonra", phonetic: "son-ra", translation: "après", category: "nouns" },
    { turkish: "önce", phonetic: "eun-dje", translation: "avant", category: "nouns" },
    { turkish: "sabah", phonetic: "sa-bah", translation: "matin", category: "nouns" },
    { turkish: "öğle", phonetic: "eu-le", translation: "midi", category: "nouns" },
    { turkish: "akşam", phonetic: "ak-cham", translation: "soir", category: "nouns" },
    { turkish: "gece", phonetic: "ge-dje", translation: "nuit", category: "nouns" },
    { turkish: "gündüz", phonetic: "gun-duz", translation: "journée", category: "nouns" },
    { turkish: "geceyarısı", phonetic: "ge-dje-ya-reu-seu", translation: "minuit", category: "nouns" },
    { turkish: "öğleden önce", phonetic: "eu-le-den eun-dje", translation: "avant-midi", category: "nouns" },
    { turkish: "öğleden sonra", phonetic: "eu-le-den son-ra", translation: "après-midi", category: "nouns" },
    { turkish: "pazartesi", phonetic: "pa-zar-te-si", translation: "lundi", category: "nouns" },
    { turkish: "salı", phonetic: "sa-leu", translation: "mardi", category: "nouns" },
    { turkish: "çarşamba", phonetic: "tchar-cham-ba", translation: "mercredi", category: "nouns" },
    { turkish: "perşembe", phonetic: "per-chem-be", translation: "jeudi", category: "nouns" },
    { turkish: "cuma", phonetic: "dju-ma", translation: "vendredi", category: "nouns" },
    { turkish: "cumartesi", phonetic: "dju-mar-te-si", translation: "samedi", category: "nouns" },
    { turkish: "pazar", phonetic: "pa-zar", translation: "dimanche", category: "nouns" },
    { turkish: "hafta sonu", phonetic: "haf-ta so-nu", translation: "week-end", category: "nouns" },
    { turkish: "hafta içi", phonetic: "haf-ta i-tchi", translation: "jour de semaine", category: "nouns" },
    { turkish: "ocak", phonetic: "o-djak", translation: "janvier", category: "nouns" },
    { turkish: "şubat", phonetic: "chu-bat", translation: "février", category: "nouns" },
    { turkish: "mart", phonetic: "mart", translation: "mars", category: "nouns" },
    { turkish: "nisan", phonetic: "ni-san", translation: "avril", category: "nouns" },
    { turkish: "mayıs", phonetic: "ma-yeus", translation: "mai", category: "nouns" },
    { turkish: "haziran", phonetic: "ha-zi-ran", translation: "juin", category: "nouns" },
    { turkish: "temmuz", phonetic: "tem-muz", translation: "juillet", category: "nouns" },
    { turkish: "ağustos", phonetic: "a-us-tos", translation: "août", category: "nouns" },
    { turkish: "eylül", phonetic: "ey-lul", translation: "septembre", category: "nouns" },
    { turkish: "ekim", phonetic: "e-kim", translation: "octobre", category: "nouns" },
    { turkish: "kasım", phonetic: "ka-seum", translation: "novembre", category: "nouns" },
    { turkish: "aralık", phonetic: "a-ra-leuk", translation: "décembre", category: "nouns" },
    { turkish: "ilkbahar", phonetic: "ilk-ba-har", translation: "printemps", category: "nouns" },
    { turkish: "yaz", phonetic: "yaz", translation: "été", category: "nouns" },
    { turkish: "sonbahar", phonetic: "son-ba-har", translation: "automne", category: "nouns" },
    { turkish: "kış", phonetic: "keuch", translation: "hiver", category: "nouns" },
    { turkish: "mevsim", phonetic: "mev-sim", translation: "saison", category: "nouns" },
    { turkish: "sıfır", phonetic: "seu-feur", translation: "zéro", category: "nouns" },
    { turkish: "bir", phonetic: "bir", translation: "un", category: "nouns" },
    { turkish: "iki", phonetic: "i-ki", translation: "deux", category: "nouns" },
    { turkish: "üç", phonetic: "utch", translation: "trois", category: "nouns" },
    { turkish: "dört", phonetic: "deurt", translation: "quatre", category: "nouns" },
    { turkish: "beş", phonetic: "bech", translation: "cinq", category: "nouns" },
    { turkish: "altı", phonetic: "al-teu", translation: "six", category: "nouns" },
    { turkish: "yedi", phonetic: "ye-di", translation: "sept", category: "nouns" },
    { turkish: "sekiz", phonetic: "se-kiz", translation: "huit", category: "nouns" },
    { turkish: "dokuz", phonetic: "do-kuz", translation: "neuf", category: "nouns" },
    { turkish: "on", phonetic: "on", translation: "dix", category: "nouns" },
    { turkish: "on bir", phonetic: "on bir", translation: "onze", category: "nouns" },
    { turkish: "on iki", phonetic: "on i-ki", translation: "douze", category: "nouns" },
    { turkish: "on üç", phonetic: "on utch", translation: "treize", category: "nouns" },
    { turkish: "on dört", phonetic: "on deurt", translation: "quatorze", category: "nouns" },
    { turkish: "on beş", phonetic: "on bech", translation: "quinze", category: "nouns" },
    { turkish: "on altı", phonetic: "on al-teu", translation: "seize", category: "nouns" },
    { turkish: "on yedi", phonetic: "on ye-di", translation: "dix-sept", category: "nouns" },
    { turkish: "on sekiz", phonetic: "on se-kiz", translation: "dix-huit", category: "nouns" },
    { turkish: "on dokuz", phonetic: "on do-kuz", translation: "dix-neuf", category: "nouns" },
    { turkish: "yirmi", phonetic: "yir-mi", translation: "vingt", category: "nouns" },
    { turkish: "otuz", phonetic: "o-tuz", translation: "trente", category: "nouns" },
    { turkish: "kırk", phonetic: "keurk", translation: "quarante", category: "nouns" },
    { turkish: "elli", phonetic: "el-li", translation: "cinquante", category: "nouns" },
    { turkish: "altmış", phonetic: "alt-meuch", translation: "soixante", category: "nouns" },
    { turkish: "yetmiş", phonetic: "yet-mich", translation: "soixante-dix", category: "nouns" },
    { turkish: "seksen", phonetic: "sek-sen", translation: "quatre-vingts", category: "nouns" },
    { turkish: "doksan", phonetic: "dok-san", translation: "quatre-vingt-dix", category: "nouns" },
    { turkish: "yüz", phonetic: "yuz", translation: "cent", category: "nouns" },
    { turkish: "iki yüz", phonetic: "i-ki yuz", translation: "deux cents", category: "nouns" },
    { turkish: "bin", phonetic: "bin", translation: "mille", category: "nouns" },
    { turkish: "iki bin", phonetic: "i-ki bin", translation: "deux mille", category: "nouns" },
    { turkish: "on bin", phonetic: "on bin", translation: "dix mille", category: "nouns" },
    { turkish: "yüz bin", phonetic: "yuz bin", translation: "cent mille", category: "nouns" },
    { turkish: "milyon", phonetic: "mil-yon", translation: "million", category: "nouns" },
    { turkish: "milyar", phonetic: "mil-yar", translation: "milliard", category: "nouns" },
    { turkish: "sayı", phonetic: "sa-yeu", translation: "nombre", category: "nouns" },
    { turkish: "rakam", phonetic: "ra-kam", translation: "chiffre", category: "nouns" },
    { turkish: "birinci", phonetic: "bi-rin-dji", translation: "premier", category: "nouns" },
    { turkish: "ikinci", phonetic: "i-kin-dji", translation: "deuxième", category: "nouns" },
    { turkish: "üçüncü", phonetic: "u-tchun-dju", translation: "troisième", category: "nouns" },
    { turkish: "dördüncü", phonetic: "deur-dun-dju", translation: "quatrième", category: "nouns" },
    { turkish: "beşinci", phonetic: "be-chin-dji", translation: "cinquième", category: "nouns" },
    { turkish: "altıncı", phonetic: "al-teun-djeu", translation: "sixième", category: "nouns" },
    { turkish: "yedinci", phonetic: "ye-din-dji", translation: "septième", category: "nouns" },
    { turkish: "sekizinci", phonetic: "se-ki-zin-dji", translation: "huitième", category: "nouns" },
    { turkish: "dokuzuncu", phonetic: "do-ku-zun-dju", translation: "neuvième", category: "nouns" },
    { turkish: "onuncu", phonetic: "o-nun-dju", translation: "dixième", category: "nouns" }
];

// Export to window for browser use
window.timeNumbers = timeNumbers;

if (typeof module !== 'undefined' && module.exports) {
    module.exports = timeNumbers;
}
