(function() {
    if (window.verbs) return; // Already loaded

    window.verbs = [
    { turkish: "Gitmek", phonetic: "ghuit-mèk", translation: "aller", category: "verbs" },
    { turkish: "Gelmek", phonetic: "ghèl-mèk", translation: "venir", category: "verbs" },
    { turkish: "Yapmak", phonetic: "yap-mak", translation: "faire", category: "verbs" },
    { turkish: "Olmak", phonetic: "ol-mak", translation: "être, devenir", category: "verbs" },
    { turkish: "Vermek", phonetic: "vèr-mèk", translation: "donner", category: "verbs" },
    { turkish: "Almak", phonetic: "al-mak", translation: "prendre, acheter", category: "verbs" },
    { turkish: "Görmek", phonetic: "gueûr-mèk", translation: "voir", category: "verbs" },
    { turkish: "Bilmek", phonetic: "bil-mèk", translation: "savoir", category: "verbs" },
    { turkish: "Demek", phonetic: "dè-mèk", translation: "dire", category: "verbs" },
    { turkish: "Kalmak", phonetic: "kal-mak", translation: "rester", category: "verbs" },
    { turkish: "Çıkmak", phonetic: "tchi-kmak", translation: "sortir", category: "verbs" },
    { turkish: "Bakmak", phonetic: "bak-mak", translation: "regarder", category: "verbs" },
    { turkish: "Girmek", phonetic: "ghir-mèk", translation: "entrer", category: "verbs" },
    { turkish: "Bulmak", phonetic: "boul-mak", translation: "trouver", category: "verbs" },
    { turkish: "Yemek", phonetic: "yè-mèk", translation: "manger", category: "verbs" },
    { turkish: "İçmek", phonetic: "itch-mèk", translation: "boire", category: "verbs" },
    { turkish: "Okumak", phonetic: "o-kou-mak", translation: "lire", category: "verbs" },
    { turkish: "Yazmak", phonetic: "yaz-mak", translation: "écrire", category: "verbs" },
    { turkish: "Söylemek", phonetic: "seû-lè-mèk", translation: "dire, raconter", category: "verbs" },
    { turkish: "Konuşmak", phonetic: "ko-nouch-mak", translation: "parler", category: "verbs" },
    { turkish: "Duymak", phonetic: "douy-mak", translation: "entendre", category: "verbs" },
    { turkish: "Dinlemek", phonetic: "din-lè-mèk", translation: "écouter", category: "verbs" },
    { turkish: "Anlamak", phonetic: "an-la-mak", translation: "comprendre", category: "verbs" },
    { turkish: "Düşünmek", phonetic: "dü-chün-mèk", translation: "penser", category: "verbs" },
    { turkish: "Sevmek", phonetic: "sèv-mèk", translation: "aimer", category: "verbs" },
    { turkish: "İstemek", phonetic: "is-tè-mèk", translation: "vouloir", category: "verbs" },
    { turkish: "Aramak", phonetic: "a-ra-mak", translation: "chercher, appeler", category: "verbs" },
    { turkish: "Başlamak", phonetic: "bach-la-mak", translation: "commencer", category: "verbs" },
    { turkish: "Bitirmek", phonetic: "bi-tir-mèk", translation: "finir, terminer", category: "verbs" },
    { turkish: "Açmak", phonetic: "atch-mak", translation: "ouvrir", category: "verbs" },
    { turkish: "Kapamak", phonetic: "ka-pa-mak", translation: "fermer", category: "verbs" },
    { turkish: "Beklemek", phonetic: "bèk-lè-mèk", translation: "attendre", category: "verbs" },
    { turkish: "Çalışmak", phonetic: "tcha-lch-mak", translation: "travailler", category: "verbs" },
    { turkish: "Oturmak", phonetic: "o-tour-mak", translation: "s'asseoir", category: "verbs" },
    { turkish: "Kalkmak", phonetic: "kalk-mak", translation: "se lever", category: "verbs" },
    { turkish: "Yatmak", phonetic: "yat-mak", translation: "se coucher", category: "verbs" },
    { turkish: "Uyumak", phonetic: "ou-you-mak", translation: "dormir", category: "verbs" },
    { turkish: "Uyanmak", phonetic: "ou-yan-mak", translation: "se réveiller", category: "verbs" },
    { turkish: "Koşmak", phonetic: "koch-mak", translation: "courir", category: "verbs" },
    { turkish: "Yürümek", phonetic: "yü-rü-mèk", translation: "marcher", category: "verbs" },
    { turkish: "Durmak", phonetic: "dour-mak", translation: "s'arrêter", category: "verbs" },
    { turkish: "Getirmek", phonetic: "ghè-tir-mèk", translation: "apporter", category: "verbs" },
    { turkish: "Götürmek", phonetic: "gueû-tür-mèk", translation: "emmener", category: "verbs" },
    { turkish: "Kullanmak", phonetic: "koul-lan-mak", translation: "utiliser", category: "verbs" },
    { turkish: "Öğrenmek", phonetic: "eu-rèn-mèk", translation: "apprendre", category: "verbs" },
    { turkish: "Öğretmek", phonetic: "eu-rèt-mèk", translation: "enseigner", category: "verbs" },
    { turkish: "Anlatmak", phonetic: "an-lat-mak", translation: "expliquer, raconter", category: "verbs" },
    { turkish: "Sormak", phonetic: "sor-mak", translation: "demander", category: "verbs" },
    { turkish: "Cevap vermek", phonetic: "djè-vap vèr-mèk", translation: "répondre", category: "verbs" },
    { turkish: "Hatırlamak", phonetic: "ha-tr-la-mak", translation: "se souvenir", category: "verbs" },
    { turkish: "Unutmak", phonetic: "ou-nout-mak", translation: "oublier", category: "verbs" },
    { turkish: "Tanımak", phonetic: "ta-n-mak", translation: "connaître", category: "verbs" },
    { turkish: "Tanışmak", phonetic: "ta-nch-mak", translation: "faire connaissance", category: "verbs" },
    { turkish: "Gülmek", phonetic: "güül-mèk", translation: "rire", category: "verbs" },
    { turkish: "Ağlamak", phonetic: "a-la-mak", translation: "pleurer", category: "verbs" },
    { turkish: "Oynamak", phonetic: "oy-na-mak", translation: "jouer", category: "verbs" },
    { turkish: "Kazanmak", phonetic: "ka-zan-mak", translation: "gagner", category: "verbs" },
    { turkish: "Kaybetmek", phonetic: "kay-bèt-mèk", translation: "perdre", category: "verbs" },
    { turkish: "Satmak", phonetic: "sat-mak", translation: "vendre", category: "verbs" },
    { turkish: "Satın almak", phonetic: "sa-tn al-mak", translation: "acheter", category: "verbs" },
    { turkish: "Ödemek", phonetic: "eu-dè-mèk", translation: "payer", category: "verbs" },
    { turkish: "Harcamak", phonetic: "har-dja-mak", translation: "dépenser", category: "verbs" },
    { turkish: "Biriktirmek", phonetic: "bi-rik-tir-mèk", translation: "économiser", category: "verbs" },
    { turkish: "Çekmek", phonetic: "tchèk-mèk", translation: "tirer", category: "verbs" },
    { turkish: "İtmek", phonetic: "it-mèk", translation: "pousser", category: "verbs" },
    { turkish: "Atmak", phonetic: "at-mak", translation: "jeter, lancer", category: "verbs" },
    { turkish: "Tutmak", phonetic: "tout-mak", translation: "tenir, attraper", category: "verbs" },
    { turkish: "Taşımak", phonetic: "ta-ch-mak", translation: "porter, transporter", category: "verbs" },
    { turkish: "Yıkamak", phonetic: "y-ka-mak", translation: "laver", category: "verbs" },
    { turkish: "Temizlemek", phonetic: "tè-miz-lè-mèk", translation: "nettoyer", category: "verbs" },
    { turkish: "Silmek", phonetic: "sil-mèk", translation: "essuyer", category: "verbs" },
    { turkish: "Düşmek", phonetic: "düch-mèk", translation: "tomber", category: "verbs" },
    { turkish: "Kırılmak", phonetic: "k-rl-mak", translation: "se casser", category: "verbs" },
    { turkish: "Kırmak", phonetic: "kr-mak", translation: "casser", category: "verbs" },
    { turkish: "Bozulmak", phonetic: "bo-zoul-mak", translation: "se gâter, tomber en panne", category: "verbs" },
    { turkish: "Tamir etmek", phonetic: "ta-mir èt-mèk", translation: "réparer", category: "verbs" },
    { turkish: "Yapmak", phonetic: "yap-mak", translation: "fabriquer", category: "verbs" },
    { turkish: "Üretmek", phonetic: "ü-rèt-mèk", translation: "produire", category: "verbs" },
    { turkish: "Pişirmek", phonetic: "pi-chir-mèk", translation: "cuire", category: "verbs" },
    { turkish: "Kesmek", phonetic: "kès-mèk", translation: "couper", category: "verbs" },
    { turkish: "Doğramak", phonetic: "do-ra-mak", translation: "hacher", category: "verbs" },
    { turkish: "Karıştırmak", phonetic: "ka-rch-tr-mak", translation: "mélanger", category: "verbs" },
    { turkish: "Eklemek", phonetic: "èk-lè-mèk", translation: "ajouter", category: "verbs" },
    { turkish: "Çıkarmak", phonetic: "tch-kar-mak", translation: "enlever, sortir", category: "verbs" },
    { turkish: "Koymak", phonetic: "koy-mak", translation: "mettre, poser", category: "verbs" },
    { turkish: "Bırakmak", phonetic: "b-rak-mak", translation: "laisser", category: "verbs" },
    { turkish: "Seçmek", phonetic: "sètch-mèk", translation: "choisir", category: "verbs" },
    { turkish: "Değiştirmek", phonetic: "dè-ich-tir-mèk", translation: "changer", category: "verbs" },
    { turkish: "Taşınmak", phonetic: "ta-chn-mak", translation: "déménager", category: "verbs" },
    { turkish: "Yaşamak", phonetic: "ya-cha-mak", translation: "vivre", category: "verbs" },
    { turkish: "Ölmek", phonetic: "eûl-mèk", translation: "mourir", category: "verbs" },
    { turkish: "Doğmak", phonetic: "do-mak", translation: "naître", category: "verbs" },
    { turkish: "Büyümek", phonetic: "bü-yü-mèk", translation: "grandir", category: "verbs" },
    { turkish: "Küçülmek", phonetic: "kü-tchü-lmèk", translation: "rétrécir", category: "verbs" },
    { turkish: "Artmak", phonetic: "art-mak", translation: "augmenter", category: "verbs" },
    { turkish: "Azalmak", phonetic: "a-zal-mak", translation: "diminuer", category: "verbs" },
    { turkish: "Uçmak", phonetic: "outch-mak", translation: "voler (dans l'air)", category: "verbs" },
    { turkish: "Yüzmek", phonetic: "yüz-mèk", translation: "nager", category: "verbs" },
    { turkish: "Gezinmek", phonetic: "ghè-zin-mèk", translation: "se promener", category: "verbs" },
];

// Export to window for browser use
window.verbs = verbs;

    // Export for Node.js if needed
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = window.verbs;
    }
})();
